# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSucess():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sucess(self):
    # Test name: sucess
    # Step # | name | target | value
    # 1 | open | /app/ | 
    self.driver.get("https://platformrc.wyscout.com/app/")
    # 2 | setWindowSize | 1280x708 | 
    self.driver.set_window_size(1280, 708)
    # 3 | type | id=login_username | ruchabhosale96@gmail.com
    self.driver.find_element(By.ID, "login_username").send_keys("ruchabhosale96@gmail.com")
    # 4 | click | id=login_password | 
    self.driver.find_element(By.ID, "login_password").click()
    # 5 | click | id=login_password | 
    self.driver.find_element(By.ID, "login_password").click()
    # 6 | type | id=login_password | pw_IndiaTest!
    self.driver.find_element(By.ID, "login_password").send_keys("pw_IndiaTest!")
    # 7 | click | id=login_button | 
    self.driver.find_element(By.ID, "login_button").click()
  
